### ISSUE TITLE
Ignoring case while checking for the response from GetCACaps message

### ISSUE THREAD

**Issue by MrLango** [jscep/jscep#137]
We are using a server that sends POSTPKIOperation as PostPkiOperation for the response from GetCACaps message. If it was not case sensitive, we can use your library. 
Right now, client doesn't recognise HTTP POST and sends a HTTP GET request as PKIOperation. This results in an error.

**Comment by seize-the-dave** [comment]
@MrLango if you want to contribute a case-insensitive comparison, I'd be happy to review it.
