### ISSUE TITLE
Order of certificates in CertStore not guaranteed after a successful enrollment

### ISSUE THREAD

**Issue by pablobill** [jscep/jscep#15]
I have only tested this on Mac OSX and Java 7.  If a scep server returns multiple certificates on a successful enroll the order of the certificates in the CertStore is not guaranteed if SUN is the security provider. See this question I posted on stackoverflow - http://stackoverflow.com/questions/19897598/bouncycastle-provider-and-java-sun-provider-interopability-issue .

Section 4.2.1 states that the issued certificate MUST be the first in the list of a Certificate Enrollment Response Message. I am sure it is but once we put it in a CertStore this is no longer the case on the platform and Java version I tested against.

This issue does not happen if BouncyCastle is the provider.  When SUN is the provider the position of certificates in the CertStore can vary between runs under identical conditions.

I now have the definitive answer, SUN CertStore uses a hash set and it provides no guarantee of order. After reading the code it seems you have a class for dealing with this - the CertStoreInspector.

**Comment by seize-the-dave** [comment]
@pablobill do you have a test case you can provide?
