### ISSUE TITLE
More flexible matching of encryption certificate

### ISSUE THREAD

**Issue by kuehne-trustable-de** [jscep/jscep#180]
We've seen problems with closed source software talking to an scep server component implementd using jscep. The problem is caused by the client reordering the RDNS in the recipient cert. Therefopre the matching of the encryptor fails.

Your current code is completely correct! Nevertheless I would suggest to implement an optional, more relaxed RecipientInfo matcher (in PkcsPkiEnvelopeDecoder.decode), e.g. by ignoring the order of the RDNs.

I could offer to build a PR. Would such an approach be option for your project? Or do you prefer **not** to fix other people's problems?

**Comment by seize-the-dave** [comment]
@kuehne-trustable-de better to be useful that correct, so a PR would be great, thank you.
