### ISSUE TITLE
make servlet optional

### ISSUE THREAD

**Issue by kuehne-trustable-de** [jscep/jscep#184]
The use of jscep in a not servlet-based is a bit tricky and some advantages (of the Spring environment) are lost of difficult to use. Especially testing is challange as the servelt ist started before the usual test frameworks have a chance to instrument the environment.

My proposal is to separate the non-servlet related code out of ScepServlet.java into a SCEP request handling class (e.g. called ScepProcessor). The ScepServlet would delegate to the ScepProcessor.
Any other framework could use the ScepProcessor directly without intering with the servlet. Useful features (like Spring security configurations) may not be cuircumvented by the servlet.

Additional requirements, e.g. support separate realms by path parameter, can be implemented easily.

My current workaround is to handle incoming reuests by Sprimg framework and delegate its HTTPRequest to the servlet. Additional parameter are forwarded to the SCEP implementation subclass using ThreadLocal. Instantiation of the servlet is deferred by the 'Lazy' annotation to enable the test framework to do the setup correctly. 
This workaround is complex and hard to understand. Security leaks (by accessing the servlet directly) may still be in place. 

If you consider the separation of functionality into ScepProcessor as a useful option I would be happy to contribute.

**Comment by seize-the-dave** [comment]
@kuehne-trustable-de can you create a PR for this work so I can review?
