### ISSUE TITLE
PkiMessageEncoder constructor hardcodes in the signature algorithm as SHA1 based

### ISSUE THREAD

**Issue by jervin** [jscep/jscep#218]
**Describe the bug**
If I use the constructor for PkiMessageEncoder where I include a certificate chain, the signature algorithm is set to SHA1withRSA with no means to change it.  I would like to be able to change it to SHA256 or better.

```
public PkiMessageEncoder(final PrivateKey signerKey,
            final X509Certificate signerId, final X509Certificate[] chain,
            final PkcsPkiEnvelopeEncoder enveloper) {
        this.signerKey = signerKey;
        this.signerId = signerId;
        this.chain = chain;
        this.enveloper = enveloper;
        this.signatureAlgorithm = "SHA1withRSA";
    }
```

**Comment by seize-the-dave** [comment]
@jervin can you create a pull request and reference this item?

**Comment by imrsk** [comment]
https://github.com/jscep/jscep/pull/219
This has been fixed
