### ISSUE TITLE
A new version release？

### ISSUE THREAD

**Issue by ICTlight** [jscep/jscep#228]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by aloopkin** [comment]
This becomes urgent !
BouncyCastle has changed its packaging from 1.71 onwards, jdk15on becoming jdk18on. We need a new JSCEP release to avoid entering dependency hell.

**Comment by ifindthanh** [comment]
I think we need to fix the vulnerabilities found by maven here
<img width="393" alt="image" src="https://user-images.githubusercontent.com/11816930/217503491-8f01370d-ceae-4309-9e74-7deb262ba04a.png">

**Comment by ifindthanh** [comment]
I think we need to fix the vulnerabilities found by maven here
<img width="556" alt="image" src="https://user-images.githubusercontent.com/11816930/217504012-9dc7f34d-d3a4-4168-b62c-99e37a1396ad.png">

**Comment by seize-the-dave** [comment]
It's been a long time since the last release.  I'll look at addressing the BC dependency too.

**Comment by seize-the-dave** [comment]
2.5.5 has been released to central.  Should be no CVEs, and BC is updated to 1.72.
