### ISSUE TITLE
Private keys to decrypt the samples

### ISSUE THREAD

**Issue by lhuynh-cs** [jscep/jscep#269]
Hi

Do you have the private keys from both client side and server side that were used to build the samples ?

Thank you

**Comment by fencepost-error** [comment]
They were just ephemeral keys generated to create the samples.  You shouldn't need them for anything since the data at every step of the process is in the samples, in other words the plaintext that's later encrypted and decrypted is already provided.

**Comment by seize-the-dave** [comment]
@lhuynh-cs if you're looking to test your SCEP implementation, there's a public server here: https://interop.redwax.eu/rs/

**Comment by lhuynh-cs** [comment]
> They were just ephemeral keys generated to create the samples. You shouldn't need them for anything since the data at every step of the process is in the samples, in other words the plaintext that's later encrypted and decrypted is already provided.

I wanted to test some code that decrypts the messages...

**Comment by fencepost-error** [comment]
Because they were just a trace from a run of a SCEP client and server six or so years ago, I don't have the keys any more.  As @seize-the-dave suggested, you'd be best off using the interop server to test against.  Alternatively, since SCEP is just CMS / S/MIME messages, if you only want to test message decryption you could test with the output of anything that'll create an encrypted CMS message.

**Comment by lhuynh-cs** [comment]
> @lhuynh-cs if you're looking to test your SCEP implementation, there's a public server here: https://interop.redwax.eu/rs/

What do you think of the following modification in PkiMessageDecoder.java to use the signer certificate to verify the response message? It is working with the Redwax server which does not include certificates in the signedData
        
        X509CertificateHolder cert;
        if (certColl.size() > 0) {
            cert = certColl.iterator().next();
        } else {
        	try {
		    cert = new X509CertificateHolder(signer.getEncoded());
		} catch (CertificateEncodingException | IOException e) {
		    throw new MessageDecodingException(e);
		}
        }
        LOGGER.debug(
                "Verifying pkiMessage using key belonging to [dn={}; serial={}]",
                cert.getSubject(), cert.getSerialNumber());
        SignerInformationVerifier verifier;
        try {
            verifier = new JcaSimpleSignerInfoVerifierBuilder().build(cert);
           ...
