### ISSUE TITLE
Corrupt pki message

### ISSUE THREAD

**Issue by friesendrywall** [jscep/jscep#27]
I dont know where to begin really, but I find that decoding the last output sent to the CA is not in a valid asn1 format.  I inserted code to save the output to file at different points, and find that the cert and request are valid, but after calling enrol, the combined output is wrong.  guiDumpASN shows at the end:

         :                     36 E2 44 AE C2 D1 D7 40 DF 07 7F 74 14 DB 34 B0
         :                     AC A6 30 E6 9B 38 13 18 DC 66 46 DB C2 26 20 E6
         :                             [ Another 584 bytes skipped ]
1216   88:                         EXTERNAL {
1218    0:                           [0]
         :                             Error: Object has zero length.
         :                             Error: Spurious EOC in definite-length item.
         :                             Error: Spurious EOC in definite-length item.
         :                             Error: Spurious EOC in definite-length item.
         :                             Error: Spurious EOC in definite-length item.
         :                             Error: Spurious EOC in definite-length item.
         :                             Error: Spurious EOC in definite-length item.
         :                             Error: Spurious EOC in definite-length item.
1235 NDEF: 

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
My code is: 

package javaapplication1;

import etc....

/**
 *
 * @author Erik
 */
public class JavaApplication1 {

        // URL of our SCEP server
    static String scepUrl = "http://bluecoatasweb.managed.entrust.com/scep/pkiclient.exe";
    //static final String sigAlg = "SHA1withRSA";
    static final String sigAlg = "MD5withRSA";
    static final int keySize = 2048;
    // Seed to our PRNG. Make sure this is initialised randomly, NOT LIKE THIS
    static final byte[] seed = "DEFG".getBytes();
    static final int validity = 1095;
    static final String iosTrustpoint = "BlueCoatIssuingCA";
    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) throws NoSuchAlgorithmException, SignatureException, InvalidKeyException, NoSuchProviderException, ClientException, OperatorCreationException, TransactionException, CertificateException, CertStoreException {
        URL url = null;
        {
        // TODO code application logic here
            org.apache.log4j.Appender T = new ConsoleAppender();
            //org.apache.log4j.Logger.getLogger(sigAlg)
            Logger.getLogger(JavaApplication1.class.getName()).setLevel(Level.FINEST);
            Handler handler = new ConsoleHandler();
            handler.setLevel(Level.ALL);
            Logger.getLogger(JavaApplication1.class.getName()).addHandler(handler);
            Logger.getLogger(JavaApplication1.class.getName()).log(Level.INFO, "Opening message.");
            Security.addProvider(new BouncyCastleProvider());
            // Generate our key pair
            KeyPairGenerator kpg = KeyPairGenerator.getInstance("RSA", "BC");
            kpg.initialize(keySize, new SecureRandom(seed));
            final KeyPair kp = kpg.genKeyPair();
            try {
                url = new URL(scepUrl);
            } catch (MalformedURLException ex) {
                Logger.getLogger(JavaApplication1.class.getName()).log(Level.FINEST, null, ex);
            }
            CertificateVerifier ocv = new OptimisticCertificateVerifier();

            // Instantiate our SCEP client
            Client scepClient = new Client(url, ocv);

            // Mandatory
            X500Principal requesterIssuer = new X500Principal("CN=jscep.org, L=Cardiff, ST=Wales, C=UK");
            BigInteger serial = BigInteger.ONE;
            Calendar calendar = Calendar.getInstance();
            calendar.add(Calendar.DATE, -1); // yesterday
            Date notBefore = calendar.getTime();
            calendar.add(Calendar.DATE, +1095); // tomorrow
            Date notAfter = calendar.getTime();
            X500Principal requesterSubject = new X500Principal("CN=jscep.org, L=Cardiff, ST=Wales, C=UK"); // doesn't need to be the same as issuer
            PublicKey requesterPubKey = kp.getPublic(); // from generated key pair
            JcaX509v1CertificateBuilder certBuilder = new JcaX509v1CertificateBuilder(requesterIssuer, serial, notBefore, notAfter, requesterSubject, requesterPubKey);

            // Optional extensions
           // certBuilder.addExtension(X509Extension.keyUsage, false, new KeyUsage(KeyUsage.digitalSignature));

            // Signing
            PrivateKey requesterPrivKey = kp.getPrivate(); // from generated key pair
            JcaContentSignerBuilder certSignerBuilder = new JcaContentSignerBuilder(sigAlg); // from above
            ContentSigner certSigner = certSignerBuilder.build(requesterPrivKey);

            X509CertificateHolder certHolder = certBuilder.build(certSigner);
            JcaX509CertificateConverter converter = new JcaX509CertificateConverter();
            X509Certificate requesterCert = converter.getCertificate(certHolder);

            X500Principal entitySubject = requesterSubject; // use the same subject as the self-signed certificate
            PublicKey entityPubKey = kp.getPublic();
            PKCS10CertificationRequestBuilder csrBuilder = new JcaPKCS10CertificationRequestBuilder(entitySubject, entityPubKey);
            DERT61String password = new DERT61String("PwlyWJQVVoE1ZL758IsDvQ==;0123456789");
            csrBuilder.addAttribute(PKCSObjectIdentifiers.pkcs_9_at_challengePassword, password);

            PrivateKey entityPrivKey = kp.getPrivate();
            JcaContentSignerBuilder csrSignerBuilder = new JcaContentSignerBuilder("SHA1withRSA");
            ContentSigner csrSigner = csrSignerBuilder.build(entityPrivKey);
            PKCS10CertificationRequest csr = csrBuilder.build(csrSigner);

            EnrollmentResponse res = scepClient.enrol(requesterCert, requesterPrivKey, csr, iosTrustpoint, "GET");

            CertStore cs = res.getCertStore();
            for (Certificate c : cs.getCertificates(null)) {
                System.out.println(c.toString());
            }
        }
    }
}

**Comment by seize-the-dave** [comment]
@friesendrywall are you still having this issue?

**Comment by friesendrywall** [comment]
Yes, but other stuff took priority so I have let this lay.

**Comment by seize-the-dave** [comment]
@friesendrywall if you get time, can you rerun your code with logging for org.jscep set to DEBUG please?

**Comment by seize-the-dave** [comment]
@friesendrywall 

I noticed in your code that you used a `DERT61String` instead of a `DERPrintableString`.  This might be the cause of your issue.
