### ISSUE TITLE
Documentation - challengePassword

### ISSUE THREAD

**Issue by kai83** [jscep/jscep#273]
The documentation is very good.
What I have not found so far, how to request the challengePassword via JScep.

Also searching in the src does not provide a description on how to request the challengePassword.

Can someone help and share if and how the challengePassword can be requested from SCEP server?

**Comment by seize-the-dave** [comment]
The challenge password should be communicated out-of-band, so there is no provision in the SCEP protocol for requesting it.

**Comment by kai83** [comment]
Thank you, @seize-the-dave for the quick reply.
Maybe that should be added to the Readme / doc as well...

Thank you for answering.
