### ISSUE TITLE
The ScepServlet should check the signature of the CSR

### ISSUE THREAD

**Issue by lhuynh-cs** [jscep/jscep#276]
We should check : 

- the own CSR signature,
- and that the CSR is signed by the requester and not by someone else
[ScepServlet.zip](https://github.com/jscep/jscep/files/11574046/ScepServlet.zip)

**Comment by kuehne-trustable-de** [comment]
In case of a renewal that's not an easy task. I would vote for leaving the CSR validation to the surrounding code.

**Comment by lhuynh-cs** [comment]
Finally, I noticed that a single SCEP client can issue CSR's for several entities.
It is the case for Ivanti EPMM : the SCEP client requests certificates for multiple Android/iOS devices

**Comment by seize-the-dave** [comment]
If this issue is no longer applicable, please can you close it?

**Comment by lhuynh-cs** [comment]
Not an issue, closed
