### ISSUE TITLE
Reg : Avoid upcasting ASN1ObjectIdentifier to DERObjectIdentifier

### ISSUE THREAD

**Issue by harishankar-gopalan** [jscep/jscep#33]
Hii,

I was trying to use the latest jar for running an SCEP server. But i ended up in the bug mentioned as "Avoid upcasting ASN1ObjectIdentifier to DERObjectIdentifier". 

I understand this is due to changes in the Bouncy Castle package, and while going through the source i also see that this has been already fixed. By cloning the latest source and building it doesnt give me the error.

I would like to have the latest jar from your side officially. Help would be highly appreciated.

Thank you Team.

**Comment by seize-the-dave** [comment]
Which version are you using at the moment?  All changes to master have been
released to Maven Central.

**Comment by harishankar-gopalan** [comment]
I used the one shown under https://code.google.com/p/jscep/downloads/detail?name=jscep-2.0.2.jar&can=2&q= . Is there a separate maven release too ? Is so can you provide me the link. Thanks for the great help.

**Comment by harishankar-gopalan** [comment]
I guess the jscep-2.2.0 is the latest release. Found it on maven. Thank You Mr. Dave.

**Comment by seize-the-dave** [comment]
You're welcome.
