### ISSUE TITLE
mvn clean install fails

### ISSUE THREAD

**Issue by Saudriel** [jscep/jscep#36]
Need to remove parent field from pom.xml to build the project with Maven.

**Comment by seize-the-dave** [comment]
@Saudriel do you have any more details?  `mvn clean install` has been working for about 4 years :smiley_cat:

**Comment by Saudriel** [comment]
Oh wow I'm sorry I meant to comment this to the fork that uses Spongycastle.

**Comment by seize-the-dave** [comment]
No worries!
