### ISSUE TITLE
GET fails when POST enabled

### ISSUE THREAD

**Issue by rajeshkarthik** [jscep/jscep#40]
Hello

 I am having a problem that all my client requests are POST as soon as I enable POST. Until now they were GET.

 When I try to process the POST requests, I am unable to get the request contents. I get null pointer exception.

java.lang.NullPointerException
	at org.jscep.server.ScepServlet.getMessageBytes(ScepServlet.java:508)
	at org.jscep.server.ScepServlet.service(ScepServlet.java:109)

How do I rightly enable both GET and POST on JSCEP?

**Comment by seize-the-dave** [comment]
Which version of jscep are you using @rajeshkarthik?

**Comment by seize-the-dave** [comment]
The line numbers for ScepServlet.java don't appear to match the source code for any tag.  Have you modified the code?

**Comment by rajeshkarthik** [comment]
I have added few debug lines. Could you please tell me how do I support both get and post for jscep

**Comment by seize-the-dave** [comment]
It already supports both.  What object is causing the NPE?

**Comment by rajeshkarthik** [comment]
The issue that I see is - when I don't explicitly enable POST in CA capabilities, I get a POST request on the server side and when I try to extract the contents - request content is null. but when I don't enable the POST, I get a GET request and am able to extract contents.

**Comment by rajeshkarthik** [comment]
I think it was too much misleading - i meant to say when I dont enable POST - i get a GET request and wirks good but when I do enable POST in CA capabilities - I always get POST and content is null

**Comment by rajeshkarthik** [comment]
any pointers on this - for jscep client - its going in POST but request content is null.

**Comment by seize-the-dave** [comment]
I can't provide any pointers without debug logs.

**Comment by rajeshkarthik** [comment]
This was related to char encoding and the POST getting rejected by tomcat. I am able to get through this by setting the encoding explicitly.
