### ISSUE TITLE
Incomming message with invalid signature will be accepted

### ISSUE THREAD

**Issue by xipki** [jscep/jscep#41]
SignerInformationVerifier verifier;
try {
   verifier = new JcaSimpleSignerInfoVerifierBuilder().build(cert);
   signerInfo.verify(verifier);
  LOGGER.debug("pkiMessage verified.");
} catch (CMSException e) {
  throw new MessageDecodingException(e);
} catch (OperatorCreationException e) {
  throw new MessageDecodingException(e);
} catch (CertificateException e) {
  throw new MessageDecodingException(e);
}

should be changed to
SignerInformationVerifier verifier;
try {
   verifier = new JcaSimpleSignerInfoVerifierBuilder().build(cert);
   if(signerInfo.verify(verifier))  {
      LOGGER.debug("pkiMessage verified.");
   }
   else  {
     throw new MessageDecodingException("invalid signature");
   }
} catch (CMSException e) {
  throw new MessageDecodingException(e);
} catch (OperatorCreationException e) {
  throw new MessageDecodingException(e);
} catch (CertificateException e) {
  throw new MessageDecodingException(e);
}

**Comment by seize-the-dave** [comment]
Could you create a pull request please?

**Comment by seize-the-dave** [comment]
Thanks xipki!

**Comment by seize-the-dave** [comment]
Thanks for your contribution @xipki
