### ISSUE TITLE
Testing the client

### ISSUE THREAD

**Issue by pauldavidgilligan-msm** [jscep/jscep#43]
Hi,

We have been using the scep client thing are going great now good job! I asked a while ago about adding in tests to your client app and you suggested mockito. Do you have an example maybe of typical data and setup for a simple test please ? Then I can expand on that.

Paul

**Comment by seize-the-dave** [comment]
Hi Paul,

I'm glad to hear you're finding jscep useful!

The two main injection points in Client are setCertStoreInspectorFactory and setTransportFactory.  Take a look at how the Client uses those and you should have a good idea how you can introduce tests.

Dave
