### ISSUE TITLE
Invoking getCACertificate and getCACapabilities in Client

### ISSUE THREAD

**Issue by adityamalik** [jscep/jscep#52]
Hey @seize-the-dave,

I noticed that in the Client class both getCACertificate and getCACapabilities are invoked from several different methods during enrollment, polling, etc. For example, during enrollment, getCACertificate is called by getEncoder and getDecoder, both of which are called by enrol. 

Was there a particular reason to handle the method calls this way? In other words, would an alternative (such as calling getCACertificate or getCACapabilities in enrol, poll, etc. and pass the necessary information to getEncoder, getDecoder) work just as well? I can imagine that since several methods use getEncoder and getDecoder it makes sense to let these two handle the certificates and capabilities themselves. 

I would like to know if there is another reason for this decision.

Thanks,
Aditya

**Comment by seize-the-dave** [comment]
@adityamalik no reason for it.  Can you open a pull request with the necessary changes for review?
