### ISSUE TITLE
Running Jscep 2.3.0 with either Java 1.6 or Java 1.7

### ISSUE THREAD

**Issue by adityamalik** [jscep/jscep#53]
Hi @seize-the-dave, 

I am working with Jscep 2.3.0 (running it with Java 1.8), and I am happy with the product. I would like to run it with an earlier version of Java, either 1.6 or 1.7; will Jscep 2.3.0 run fine with these versions? What is the minimum Java version required to run Jscep?

Thanks,
Aditya

**Comment by seize-the-dave** [comment]
I'm not sure.  I'm pretty sure it out to run with 6+.

Dave
