### ISSUE TITLE
Question : Supported versions/vendors of Java

### ISSUE THREAD

**Issue by sbose78** [jscep/jscep#63]
Hi,
Could you please tell me if we know which versions/vendors of Java is supported for use with JSCEP ? I was hoping the readme would throw some light on that. I could help with PRs to add the info in the readme if you think that's a good idea.

I tried out with Oracle Java 8 and the tests ran fine. Do you use any other 'tests' to certify the Java version/vendor ?

**Comment by seize-the-dave** [comment]
No, it just builds against the latest JDK.  Feel free to add JDKs to
.travis.yml in a PR.

Dave

**Comment by sbose78** [comment]
Thanks, I shall keep this open and assign it to me. 
I will ask you for further assistance  as/when necessary.

**Comment by sbose78** [comment]
Partially taken care in https://github.com/jscep/jscep/pull/65
