### ISSUE TITLE
Add support for AES-256 and AES-192

### ISSUE THREAD

**Issue by sbose78** [jscep/jscep#64]
Currently, supported symmetric cipher algorithms are DES, 3-DES.
This issue will be tracking the addition of support for AES-256.

( I am taking up the development for this ).

Potential pitfalls:
- might need unrestricted policy jars. ( Applies for AES-192 and AES-256 )

**Please do not close this**

**Comment by oleg-alexeyev** [comment]
Hi!
What about supporting AES in GetCACaps in ScepServlet? Currently Capability enum misses it.
According to https://tools.ietf.org/html/draft-gutmann-scep-03, there is now "AES" keyword.

**Comment by seize-the-dave** [comment]
@oleg-alexeyev: can you create a PR?
