### ISSUE TITLE
How to handle Attribute Certificates

### ISSUE THREAD

**Issue by Blackjack92** [jscep/jscep#69]
Hello,
is it also possible to handle Attribute Certificates (ACs)) via JSCEP? - Because JSCEP supports the `X509Certificate` from `java.security.cert` and this class contains a `getPublicKey` method, which is not part of the AC. So, should the `X509Certificate` be used without a public key for the AC or should a new `AttributeCertificate` be implemented and the JSCEP enhanced?

**Comment by seize-the-dave** [comment]
I'm sorry, but this is beyond the scope of this library.  Please feel free to continue this discussion on our mailing list: jscep-support@googlegroups.com
