### ISSUE TITLE
Version based on JDK 11 and Spongycastle

### ISSUE THREAD

**Issue by CarvalhoLeonardo** [jscep/jscep#95]
Hi.

I'm testing the use of this project on one interacting with the Java SDK for Hyperledger Sawtooth. The tests are running. _(they are awesome, congrats!)_

But I would need to use [Spongy Castle](https://rtyley.github.io/spongycastle/) jars, to keep compatibility, so, I doubt a push request would be advisable.

What would suggest when I push my changes? A "bouncycastle" suffix, or a branch on this project?

Thank you.

**Comment by seize-the-dave** [comment]
Thanks @CarvalhoLeonardo!  Have you seen this here: https://groups.google.com/forum/embed/#!topic/jscep-support/FtUrH1JFJCA

I think a fork is probably more appropriate than a branch if that suits you?
