### ISSUE TITLE
randomNonce in SCEP messages are not allowed per RFC

### ISSUE THREAD

**Issue by bb-froggy** [jscep/jscep#96]
**Describe the bug**
[Version 13 of the SCEP RFC](https://tools.ietf.org/html/draft-gutmann-scep-13#section-3.2.1) specifies in Section 3.2.1 which attributes are allowed and/or required in a SCEP message. I see a senderNonce (2 16 840 1 113733 1 9 5) and recipientNonce (2 16 840 1 113733 1 9 6), but no randomNonce (1 2 840 113549 1 9 25 3). However, the sample messages seem to include a randomNonce in both the request as well as the reply.

**To Reproduce**
1. Open sample [scep_req2](../blob/master/src/samples/scep_req2.txt) or [scep_resp2](../blob/master/src/samples/scep_resp2.txt).
2. Search for the string "1 2 840 113549 1 9 25 3"

**Expected behavior**
The attribute randomNonce should not appear in these messages.

**Comment by fencepost-error** [comment]
It doesn't define what's allowed, merely the minimum that's required, you can add any extra attributes you like.  In this case the messages were generated by an implementation that always adds a randomNonce (to deal with signing predictable messages if there are weaknesses in the hash function used), which is perfectly valid - think of it as a test of an implementation's ability to handle arbitrary attributes.
