### ISSUE TITLE
Scep enrollment getting failed in cisco Router using an RA scep server

### ISSUE THREAD

**Issue by bharathbofl** [jscep/jscep#97]
Feb 22 06:12:29.940: CRYPTO_PKI: Prepare global revocation service providers
*Feb 22 06:12:29.954: ../cert-c/source/p7spprt.c(633) : E_ENCRYPT_ALG_NOT_SUPPORTED : message encryption algorithms not supported
*Feb 22 06:12:29.962:  Invalid signer count value 0
*Feb 22 06:12:29.962: CRYPTO_PKI: status = 0x762(E_ENCRYPT_ALG_NOT_SUPPORTED : message encryption algorithms not supported): pkcs7 verify data returned status
*Feb 22 06:12:29.962: CRYPTO_PKI: Remove global revocation service providers
*Feb 22 06:12:29.963: CRYPTO_PKI: status = 0x762(E_ENCRYPT_ALG_NOT_SUPPORTED : message encryption algorithms not supported): failed to verify
*Feb 22 06:12:29.963: CRYPTO_PKI: status = 0x762(E_ENCRYPT_ALG_NOT_SUPPORTED : message encryption algorithms not supported): failed to process the inner content
*Feb 22 06:12:29.963: %PKI-6-CERTFAIL: Certificate enrollment failed.

**Comment by seize-the-dave** [comment]
@bharathbofl do you know which algorithms aren't supported, and what your SCEP server is using?
