### ISSUE TITLE
isSelfSigned method fails for hybrid certificate verification

### ISSUE THREAD

**Issue by michelebortolato** [jscep/jscep#98]
**Describe the bug**
I cannot renew an (RSA) certificate if it is emitted by an EC CA the exception returned is:

```
Caused by: org.jscep.client.ClientException: org.bouncycastle.cert.CertException: unable to process signature: exception on setup: java.security.InvalidKeyException: cannot identify EC public key.
	at org.jscep.client.Client.isSelfSigned(Client.java:651)
	at org.jscep.client.Client.enrol(Client.java:604)
	at org.jscep.client.Client.enrol(Client.java:575)
	....
	... 21 more
```

**To Reproduce**
Call Client.isSelfSigned with an RSSA Certificate issued with an EC CA

**Expected behavior**
The method isSelfSigned shout catch the proper exception handling the correct exception

**Comment by seize-the-dave** [comment]
Hi @michelebortolato, what exception class are you expecting?

**Comment by michelebortolato** [comment]
In this case Client.isSelfSigned should catch the proper exception and return false, or the enroll process will fail.

**Comment by seize-the-dave** [comment]
@michelebortolato could you provide a pull request for this?

**Comment by michelebortolato** [comment]
I should give you an renew request from a RSA certificate issued by an ec certificate.. a bit trycky i suppose. i shuld play with openssl a bit...

**Comment by michelebortolato** [comment]
whith this certificate 
`-----BEGIN CERTIFICATE-----
MIICgjCCAeMCAQEwCgYIKoZIzj0EAwIwRTELMAkGA1UEBhMCSVQxEzARBgNVBAgM
ClNvbWUtU3RhdGUxETAPBgNVBAoMCFRFU1RfT1JHMQ4wDAYDVQQDDAVDTjEyMzAe
Fw0xOTA0MTIwODM1MTJaFw0yMDA0MTEwODM1MTJaMEUxCzAJBgNVBAYTAklUMRMw
EQYDVQQIDApTb21lLVN0YXRlMRAwDgYDVQQKDAdSU0FfT1JHMQ8wDQYDVQQDDAZS
U0FfQ04wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDJB9l5lV2LRMSw
mB82yEw6sfiBZYf8jRlW9xWbDgXyQiHzgIy0c1azanjozfPP7rHn7EMfmoLLUuZV
4AIGeQfg5sVlSyvWgHqMEhSyITrKSNS31MCDGcRYgjY2Szvix9+qoGZ19VPEXN1s
W3EBEvvwt5Hc2kv8jO36HW6K0eVeDAtTndXwweryRKoXu4Hx/gHoqA4/VCp8zvJP
8H5yZo4YmeMBtclqEj+Apb01pewbdhImeVDu2RWKp7Buogzuf4PpLCztOXxKGFiq
TVURgn6N4mTcmYMAkH+qXFN0xUZwWE4EJChxaqMQf4HuT88CzkZOyLjUFZ/+7LzL
GqEyPuRXAgMBAAEwCgYIKoZIzj0EAwIDgYwAMIGIAkIBOala4M+JkBUjApdOowtA
p42mtNOeZPycrVvI5R62tfoKcgA5TnwliRyW/tCGuoicKP8+SDCr0Clt64tPcBCV
nXMCQgEl3lvI2uCLn+kibBplqjbf/iSZDjvoG9oLzdBIiohFg93pfbccq2Bt1tM5
/EBfbwCe66u03ZCtGuexI04r/ioDfQ==
-----END CERTIFICATE-----
`

as parameter into is SelfSIgned method i obtain the error signaled.

i sugges a modification like this:

`  private boolean jScepIsSelfSigned(final X509Certificate cert)
      throws ClientException {
    try {
      JcaX509CertificateHolder holder = new JcaX509CertificateHolder(cert);
      ContentVerifierProvider verifierProvider = new JcaContentVerifierProviderBuilder()
          .build(holder);

      return holder.isSignatureValid(verifierProvider);
    } catch (RuntimeOperatorException e) {
      if(e.getCause() instanceof  SignatureException) {
        LOGGER.warn("SignatureException detected so we consider that the certificate is not self signed");
        return false;
      }
      throw new ClientException(e);
    }    catch (CertException e) {
      if(e.getCause() instanceof OperatorCreationException && e.getCause().getCause() instanceof InvalidKeyException) {
        LOGGER.warn("CertException detected so we consider that the certificate is not self signed");
        return false;
      }
      throw new ClientException(e);
    } catch (Exception e) {
      throw new ClientException(e);
    }
  }`
